name: Deploy via ftp
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: himsoft-ftp-deploy
      uses: HimoSoft/ftp-deploy@v1.1.0
      with:
        host: ftp.hybridsoft.com.ng
        user: hybridso
        password: Ayoshol@123
        localDir: "."
        remoteDir: "public_html/laracicd"


# on:
#   push:
#     branches:
#       - main

# name: 🚀 Deploy website on push
# jobs:
#   web-deploy:
#     name: 🎉 Deploy
#     runs-on: ubuntu-latest
#     steps:
#     - name: 🚚 Get latest code
#       uses: actions/checkout@v2.3.2
#       with:
#         node-version: '16.x'
    
#     - name: 📂 Sync files
#       uses: SamKirkland/FTP-Deploy-Action@4.0.0
#       with:
#         server: ftp.hybridsoft.com.ng
#         username: hybridso
#         password: Ayoshol@123 
#         server-dir: /public_html/laracicd/ 
